### PR TITLE
Fix for Xcode 12

### PR DESCRIPTION
**Pull request by Fabezi**
Fix ambiguous Byte namespace for Xcode 12

### CODE REVIEW

**Comment by Strobocop** [comment]
@stephan-tolksdorf Any chance we could get this PR merged? I am in need of this fix as well.

**Comment by barMapprosing** [comment]
Joining @Strobocop on this, we need this fix as well.

**Comment by stephan-tolksdorf** [comment]
I'll take a look this weekend.

**Comment by stephan-tolksdorf** [comment]
I've fixed the issue by not using std::byte. Does that work for you?

**Pull request closed without merging**
